### ISSUE TITLE
US05 - Salvamento dos dados

### ISSUE THREAD

**Issue by WashingtonBispo** [UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS#132]
## Descrição

Eu, como um vendedor, desejo que meus dados (nome, apelido (nome de usuário), email e senha) sejam salvos para que eu consiga utilizar o sistema de maneira segura e eficaz, e possa ser identificado por outros usuários.

## Prioridade

Muito alta

## Rastreabilidade

RF-25

## Critérios de Aceitação
- [x] Os dados estão salvos no sistema corretamente?
- [x] Os dados utilizam os campos adequados, de modo a otimizar o espaço de armazenamento?
- [x] A senha é salva criptografada?

**Comment by Rhuancpq** [comment]
US feita
