### ISSUE TITLE
US09 - Cadastro de anúncio

### ISSUE THREAD

**Issue by WashingtonBispo** [UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS#133]
## Descrição

Eu, como um usuário, desejo cadastrar um novo anúncio para que eu consiga colocar um jogo para troca ou venda.

## Prioridade

Muito alta

## Rastreabilidade

RF-08

## Critérios de Aceitação
- [ ] O anúncio é salvo na base de dados corretamente?
- [ ] Os campos necessários são informados?
- [ ] O anúncio é criado com o estado válido?

**Comment by igor-paiva** [comment]
A issue não foi finalizada na sprint e foi movida para a próxima para ser completada
