### ISSUE TITLE
Primeira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS#37]
Olá Pessoal!

O Grupo 07 irá avaliar o Grupo 01 nessa primeira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Base) da trilha do Moodle, e procurar por "Primeira Avaliação por Pares".

Atenciosamente.

**Comment by thiagolopess** [comment]
Certo, professora! Obrigado!
