### ISSUE TITLE
Segunda Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS#92]
Olá Pessoal!

O Grupo 07 irá avaliar o Grupo 06 nessa segunda avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Modelagem) da trilha do Moodle, e procurar por "Segunda Avaliação por Pares".

Atenciosamente.

**Comment by thiagolopess** [comment]
Feito!
